# Supervised Learning Model Evaluation Lab

Complete the exercises below to solidify your knowledge and understanding of supervised learning model evaluation.

In [1]:
import pandas as pd

## Regression Model Evaluation

In [2]:
from sklearn.datasets import load_boston

data = load_boston()

X = pd.DataFrame(data["data"], columns=data["feature_names"])
y = pd.DataFrame(data["target"], columns=['MEDV'])

data = pd.concat([X, y], axis=1)

C:\ANACONDA\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function load_boston is deprecated; `load_boston` is deprecated in 1.0 and will be removed in 1.2.

    The Boston housing prices dataset has an ethical problem. You can refer to
    the documentation of this function for further details.

    The scikit-learn maintainers therefore strongly discourage the use of this
    dataset unless the purpose of the code is to study and educate about
    ethical issues in data science and machine learning.

    In this special case, you can fetch the dataset from the original
    source::

        import pandas as pd
        import numpy as np


        data_url = "http://lib.stat.cmu.edu/datasets/boston"
        raw_df = pd.read_csv(data_url, sep="\s+", skiprows=22, header=None)
        data = np.hstack([raw_df.values[::2, :], raw_df.values[1::2, :2]])
        target = raw_df.values[1::2, 2]

    Alternative datasets include the California housing dataset (i.e.
    :fun

## 1. Split this data set into training (80%) and testing (20%) sets.

The `MEDV` field represents the median value of owner-occupied homes (in $1000's) and is the target variable that we will want to predict.

In [3]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

## 2. Train a `LinearRegression` model on this data set and generate predictions on both the training and the testing set.

In [4]:
from sklearn.linear_model import LinearRegression

regression = LinearRegression()

# Entrenar el modelo en el conjunto de entrenamiento
regression.fit(X_train, y_train)

# Generar predicciones en el conjunto de entrenamiento y en el conjunto de prueba
train_predictions = regression.predict(X_train)
test_predictions = regression.predict(X_test)

## 3. Calculate and print R-squared for both the training and the testing set.

In [7]:
from sklearn.metrics import r2_score

train_r2 = r2_score(y_train, train_predictions)
test_r2 = r2_score(y_test, test_predictions)

In [9]:
train_r2

0.7508856358979672

In [10]:
test_r2

0.6687594935356306

## 4. Calculate and print mean squared error for both the training and the testing set.

In [12]:
from sklearn.metrics import mean_squared_error

train_mse = mean_squared_error(y_train, train_predictions)
test_mse = mean_squared_error(y_test, test_predictions)

In [13]:
train_mse

21.641412753226323

In [14]:
test_mse

24.29111947497362

## 5. Calculate and print mean absolute error for both the training and the testing set.

In [15]:
from sklearn.metrics import mean_absolute_error

train_mae = mean_absolute_error(y_train, train_predictions)
test_mae = mean_absolute_error(y_test, test_predictions)

In [16]:
train_mae

3.3147716267832266

In [17]:
test_mae

3.18909196588785

## Classification Model Evaluation

In [18]:
from sklearn.datasets import load_iris

data = load_iris()

X = pd.DataFrame(data["data"], columns=data["feature_names"])
y = pd.DataFrame(data["target"], columns=["class"])

data = pd.concat([X, y], axis=1)

## 6. Split this data set into training (80%) and testing (20%) sets.

The `class` field represents the type of flower and is the target variable that we will want to predict.

In [19]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

X_train.shape

(120, 4)

In [20]:
y_train.shape

(120, 1)

In [21]:
X_test.shape

(30, 4)

In [22]:
y_test.shape

(30, 1)

## 7. Train a `LogisticRegression` model on this data set and generate predictions on both the training and the testing set.

In [23]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression(random_state=42)
model.fit(X_train, y_train)

train_predictions = model.predict(X_train)
test_predictions = model.predict(X_test)

C:\ANACONDA\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\ANACONDA\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


## 8. Calculate and print the accuracy score for both the training and the testing set.

In [24]:
from sklearn.metrics import accuracy_score

train_accuracy = accuracy_score(y_train, train_predictions)
test_accuracy = accuracy_score(y_test, test_predictions)

In [25]:
train_accuracy

0.975

In [26]:
test_accuracy

1.0

## 9. Calculate and print the balanced accuracy score for both the training and the testing set.

In [27]:
from sklearn.metrics import balanced_accuracy_score

train_balanced_accuracy = balanced_accuracy_score(y_train, train_predictions)
test_balanced_accuracy = balanced_accuracy_score(y_test, test_predictions)

In [28]:
train_balanced_accuracy

0.975609756097561

In [29]:
test_balanced_accuracy

1.0

## 10. Calculate and print the precision score for both the training and the testing set.

In [30]:
from sklearn.metrics import precision_score

train_precision = precision_score(y_train, train_predictions, average='macro')
test_precision = precision_score(y_test, test_predictions, average='macro')

In [31]:
train_precision

0.9761904761904763

In [32]:
test_precision

1.0

## 11. Calculate and print the recall score for both the training and the testing set.

In [33]:
from sklearn.metrics import recall_score

train_recall = recall_score(y_train, train_predictions, average='macro')
test_recall = recall_score(y_test, test_predictions, average='macro')

In [34]:
train_recall

0.975609756097561

In [35]:
test_recall

1.0

## 12. Calculate and print the F1 score for both the training and the testing set.

In [36]:
from sklearn.metrics import f1_score

train_f1 = f1_score(y_train, train_predictions, average='macro')
test_f1 = f1_score(y_test, test_predictions, average='macro')

In [37]:
train_f1

0.9749960931395533

In [38]:
test_f1

1.0

## 13. Generate confusion matrices for both the training and the testing set.

In [39]:
from sklearn.metrics import confusion_matrix

train_cm = confusion_matrix(y_train, train_predictions)
print("Matriz de confusión en el conjunto de entrenamiento:\n", train_cm)

test_cm = confusion_matrix(y_test, test_predictions)
print("\nMatriz de confusión en el conjunto de prueba:\n", test_cm)

Matriz de confusión en el conjunto de entrenamiento:
 [[40  0  0]
 [ 0 38  3]
 [ 0  0 39]]

Matriz de confusión en el conjunto de prueba:
 [[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]


## Bonus: For each of the data sets in this lab, try training with some of the other models you have learned about, recalculate the evaluation metrics, and compare to determine which models perform best on each data set.