# Supervised Learning Model Evaluation Lab

Complete the exercises below to solidify your knowledge and understanding of supervised learning model evaluation.

In [12]:
import pandas as pd
import numpy as np

## Regression Model Evaluation

In [13]:
from sklearn.datasets import load_boston
data = load_boston()
X = pd.DataFrame(data["data"], columns=data["feature_names"])
y = pd.DataFrame(data["target"], columns=['MEDV'])

## 1. Split this data set into training (80%) and testing (20%) sets.

The `MEDV` field represents the median value of owner-occupied homes (in $1000's) and is the target variable that we will want to predict.

In [14]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

## 2. Train a `LinearRegression` model on this data set and generate predictions on both the training and the testing set.

In [15]:
from sklearn.linear_model import LinearRegression
lr_model = LinearRegression().fit(X_train, y_train)
y_pred_train = lr_model.predict(X_train)
y_pred_test = lr_model.predict(X_test)

## 3. Calculate and print R-squared for both the training and the testing set.

In [16]:
from sklearn.metrics import r2_score
pred_train = lr_model.predict(X_train)
print(r2_score(y_pred_train, pred_train))

pred_test = lr_model.predict(X_test)
print(r2_score(y_pred_test, pred_test))

1.0
1.0


## 4. Calculate and print mean squared error for both the training and the testing set.

In [17]:
from sklearn.metrics import mean_squared_error
print('train:',mean_squared_error(y_train, y_pred_train))
print('test:',mean_squared_error(y_test, y_pred_test))

train: 22.107996490504675
test: 22.343972911333683


## 5. Calculate and print mean absolute error for both the training and the testing set.

In [18]:
from sklearn.metrics import mean_absolute_error
print('train:',mean_absolute_error(y_train, y_pred_train))
print('test:',mean_absolute_error(y_test, y_pred_test))

train: 3.338221736936219
test: 3.3782795667530228


## Classification Model Evaluation

In [2]:
import pandas as pd
import numpy as np

In [24]:
from sklearn.datasets import load_iris
data = load_iris()
X = pd.DataFrame(data["data"], columns=data["feature_names"])
y = pd.DataFrame(data["target"], columns=["class"])

## 6. Split this data set into training (80%) and testing (20%) sets.

The `class` field represents the type of flower and is the target variable that we will want to predict.

In [27]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=50)

## 7. Train a `LogisticRegression` model on this data set and generate predictions on both the training and the testing set.

In [39]:
from sklearn.linear_model import LogisticRegression
lr_model = LogisticRegression(max_iter=1000).fit(X_train, y_train.values.ravel())
y_pred_train = lr_model.predict(X_train)
y_pred_test = lr_model.predict(X_test)

## 8. Calculate and print the accuracy score for both the training and the testing set.

In [40]:
from sklearn.metrics import accuracy_score
print('train : ', accuracy_score(y_train, y_pred_train))
print('test : ', accuracy_score(y_test, y_pred_test))

train :  0.975
test :  0.9666666666666667


## 9. Calculate and print the balanced accuracy score for both the training and the testing set.

In [41]:
from sklearn.metrics import balanced_accuracy_score
print('train : ', balanced_accuracy_score(y_train, y_pred_train))
print('test : ', balanced_accuracy_score(y_test, y_pred_test))

train :  0.9743260590500641
test :  0.9722222222222222


## 10. Calculate and print the precision score for both the training and the testing set.

In [43]:
from sklearn.metrics import precision_score
print('train : ', precision_score(y_train, y_pred_train, average='weighted'))
print('test : ', precision_score(y_test, y_pred_test, average='weighted'))

train :  0.9751716001716001
test :  0.9700000000000001


## 11. Calculate and print the recall score for both the training and the testing set.

In [47]:
from sklearn.metrics import recall_score
print('train : ', recall_score(y_train, y_pred_train, average='weighted'))
print('test : ', recall_score(y_test, y_pred_test, average='weighted'))

train :  0.975
test :  0.9666666666666667


## 12. Calculate and print the F1 score for both the training and the testing set.

In [48]:
from sklearn.metrics import f1_score
print('train : ', f1_score(y_train, y_pred_train, average='weighted'))
print('test : ', f1_score(y_test, y_pred_test, average='weighted'))

train :  0.9749839357429718
test :  0.9668192219679634


## 13. Generate confusion matrices for both the training and the testing set.

In [51]:
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_train, y_pred_train))
print()
print(confusion_matrix(y_test, y_pred_test))

[[41  0  0]
 [ 0 36  2]
 [ 0  1 40]]

[[ 9  0  0]
 [ 0 11  1]
 [ 0  0  9]]


In [39]:
from sklearn.linear_model import LogisticRegression
lr_model = LogisticRegression(max_iter=1000).fit(X_train, y_train.values.ravel())
y_pred_train = lr_model.predict(X_train)
y_pred_test = lr_model.predict(X_test)

## Bonus: For each of the data sets in this lab, try training with some of the other models you have learned about, recalculate the evaluation metrics, and compare to determine which models perform best on each data set.